### ISSUE TITLE
Website seems down [Search Issues Remain]

### ISSUE THREAD

**Issue by ZanderBrown** [flobrosch/valadoc-org#52]
http://www.valadoc.org/ is showing the "Apache2 Debian Default Page" i havent been able to find anything about this anywhere else so i decided it was best to report this.
![image](https://cloud.githubusercontent.com/assets/17074021/15635967/df3fab72-25e7-11e6-9250-b154d7025405.png)

**Comment by ZanderBrown** [comment]
It's now showing a web hosting placeholder
![image](https://cloud.githubusercontent.com/assets/17074021/15636061/29f3a710-25eb-11e6-8494-eafa5f564695.png)

**Comment by ghost** [comment]
@ZanderBrown I'm having exactly the same issue. I was looking for a mirror of the site but was not able to find one.

**Comment by benwaffle** [comment]
mirror: http://valadoc.valadate.org ﻿

**Comment by ghost** [comment]
@benwaffle Thanks so much!

**Comment by ZanderBrown** [comment]
![image](https://cloud.githubusercontent.com/assets/17074021/15713360/0cd5dc6e-280e-11e6-8fb9-9bba785749bd.png)
Not sure it's an improvement but it's a different placeholder page (see bottom right) so I'm assuming some progress has been made

**Comment by ZanderBrown** [comment]
ok so the site seems to be back up but I haven't closed this issue because search & tooltips result in SQL errors.

**Comment by danirabbit** [comment]
@ZanderBrown sorry about the inconvenience, we'll get it sorted ASAP

**Comment by ZanderBrown** [comment]
it seems tooltips are functional search not so much
![image](https://cloud.githubusercontent.com/assets/17074021/15726076/d2938360-2846-11e6-818e-06a0e54a4847.png)

**Comment by supercamel** [comment]
Hello, I'm sure you guys are working on this and thank you for the link to the mirror site, but the functional search is broken for me too. Cheers!

**Comment by roojs** [comment]
I suspect search is down, as the sphinx api has changed quite a bit.

sphinx.conf
-> add searchd deamon settings.
-        config.printf ("searchd {\n");
-               config.printf ("\tlisten =51413\n");
-               config.printf ("\tpid_file = /var/run/searchd.pid\n");
              config.printf ("}\n");
              config.printf ("\n\n");

-> remove old options
-               config.printf ("\tcharset_type = utf-8\n");
-               config.printf ("\tenable_star = 1\n");

-> change paths - fix them
-               config.printf ("\tpath = /var/lib/sphinx/sphinx-%s-%s\n", prefix, name);
-               config.printf ("\tpath = /var/lib/sphinx/sphinx-main\n");

-> /sphinx/sphinx.xsl  -- remove str2ordianl
-       <sphinx:attr name="type" type="str2ordinal" />
-       <sphinx:attr name="type" type="string" />

run
sudo indexer --config sphinx.config --all
sudo searchd --config sphinx.conf

Since the indexed files is a bit flakey  I modified allpkgs's to be generated
+$res = mysqli_query($mysqli, "SHOW TABLES");
+
+$pkgs= array();
+while ($row = $res->fetch_assoc()) {
-    $pkgs[] = $row['Index'];
-   
  +}
  +$allpkgs = implode(',', $pkgs);
  +
  +

Then the query format has changed slighly (no css? and @weight become WEIGHT()

-if (!($q = $mysqli->query("SELECT type, css, name.....  ..... ORDER BY @weight DESC, {$orderby} ....")))
+
+$qq = "SELECT type, name, shortdesc, path, signature, typeorder, {$orderby}
+
-        FROM {$allpkgs}
-            WHERE     MATCH('{$query}')
-            ORDER BY  WEIGHT()  DESC, {$orderby} ASC, typeorder ASC
-            LIMIT {$offset},20 OPTION ranker=proximity{$indexweights}";
  +//echo $qq;
  +if (!($q = $mysqli->query($qq)))

Note also modified generator.vala to just 'return' rather than die when valadoc errors.
Otherwise I'm stopping/ finding installing/fixing  etc.. constantly when trying to build...
*\* it should probably just report what failed at the end.. and let you decide if you need to fix it.

@@ -860,6 +860,7 @@ public class Valadoc.IndexGenerator : Valadoc.ValadocOrgDoclet {
                                }
                        } catch (SpawnError e) {
                                stdout.printf ("ERROR: Can't generate documentation for %s. See LOG for details.\n", pkg.name);
-                return;
                              throw e;
                      }

@@ -912,6 +913,7 @@ public class Valadoc.IndexGenerator : Valadoc.ValadocOrgDoclet {
                } catch (SpawnError e) {
                        stdout.printf ("ERROR: Can't generate documentation for %s. See LOG for details.\n", pkg.name);
                        stdout.printf ("%s\n", e.message);
-            return;
                      throw e;
              } finally {
                      if (delete_wiki_path) {

**Comment by roojs** [comment]
While it's down feel free to use this http://valadoc.roojs.com

**Comment by benwaffle** [comment]
or http://valadoc.valadate.org

**Comment by alsoijw** [comment]
There are two problems with valadoc.org . First problem is that search don't work. Second problem the problem is characteristic of valadoc.org valadoc.roojs.com and valadate.org . If I copy link to some method or property and insert in address bar or open some hyperlink with middle button click, I will have 404 error. Please, fix it.

**Comment by ZanderBrown** [comment]
@alsoijw see #56

**Comment by craigbarnes** [comment]
> Please, fix it.

Are you making demands of other people's free time?

**Comment by benwaffle** [comment]
http://valadoc.org/ is fixed! Now [hosted](http://blog.elementary.io/post/152967321211/were-now-hosting-valadocorg) by elementary

**Comment by ZanderBrown** [comment]
Sorry i only just noticed it was back up.
